# Generated by Django 4.0.4 on 2022-06-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
