# Generated by Django 4.0.4 on 2022-06-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0003_remove_productos_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petshop', to='petshop.categoria'),
        ),
    ]
